version: '2'
services:
  web:
      build: .
      ports:
        - 80:80
      links:
        - php
      depends_on:
        - php
      volumes_from:
        - php
  php:
      build: ./docker
      volumes:
        - .:/var/www/laravel
